### ISSUE TITLE
ASCII notation for linear function type constructor

### ISSUE THREAD

**Issue by jeltsch** [tweag/ghc#8] opened 2017-08-18 21:32 UTC
There is a need for an ASCII equivalent of `⊸`. In some article about the linear types extension, the author used the notation `-o`. I want to strongly advise against this notation. It would mean having a letter as part of an operator, which would be a very awkward case of stealing syntax. A consequence would be that the negation of variable `o` would have to be written `- o` (that is, with a space between `-` and `o`).

There are other cases of stealing syntax already. A very prominent one is the syntax for hierarchical module names, because of which the compositions of data constructors `A` and `B` cannot be written `A.B`. However, it is the natural thing to put spaces around infix operators; so the working alternative `A . B` is what you should use anyhow. The situation is opposite with `-o` as the lollipop ASCII equivalent, since the natural way of writing the negation of `o` is `-o`, not `- o`.

I propose to adopt one of the following solutions:

 1. Use `-+` as the ASCII variant. It looks a bit like an arrow and a bit like `⊸`.
 2. Use `~>` as the ASCII variant and `↝` as the Unicode variant (instead of `⊸`). This way, both the ASCII and the Unicode variant look very similar and look like arrows. Unfortunately, `~>` is difficult to distinguish from `->`, and `↝` is not the standard symbol for linear functions.
 3. Use `-*` as the ASCII variant. It resembles the magic wand operator from the logic of bunched implications and separation logic, which is similar to ⊸. Unfortunately, the star `*` is pretty high in most fonts, resulting in `-*` looking awkward.

I prefer Option 1.

There has been [a discussion on the GHC developers mailing list on this topic](https://mail.haskell.org/pipermail/ghc-devs/2017-July/014392.html).

**Comment by mb64** [comment] 2017-09-02 18:12
I've been reading about linear functions recently, and I'd like to point out another notation I've seen that isn't on the list, for the sake of another option: in [a SOH tutorial](https://www.schoolofhaskell.com/user/mutjida/typed-tagless-final-linear-lambda-calculus) about implementing a linear lambda calculus interpreter, the author uses `-<>` as a linear arrow.  This has the benefit of (at least somewhat) looking like a circle at the end, and being only symbols.

(As a symbol-unrelated addendum, another syntax used there to explicitly denote lambdas as linear: `\x ⊸ ...` in addition to `\x -> ...` would be interesting to include in this.)

**Comment by jeltsch** [comment] 2017-09-02 23:00
Using `-<>` for `⊸` was also proposed in [that discussion on the GHC developers mailing list](https://mail.haskell.org/pipermail/ghc-devs/2017-July/014392.html). However, as I already wrote in that thread, the `<>` part seems to be a bit heavy compared to the little `-`.

**Comment by jeltsch** [comment] 2017-09-02 23:06
I do not know whether the notation `λ x ⊸ e` is a good idea. It gives us a linear variant of `λ x → e`, but there is no linear variant of the binding syntax `f x = e`. Maybe we should not think of the arrows in abstractions (“λ-expressions”) as being the same as the arrows in types, but as being analogous to the arrows in, say, case expressions (as in `case of e where p → x`).

**Comment by aspiwack** [comment] 2017-09-05 08:29
I must say that I dislike `-<>` even more than `-o`.

I think @jeltsch's option 2 is not the best, because `⊸` is the standard notation for linear arrows in the literature, and I see no reason to change this. It's been Haskell's tradition to try and vaguely resemble the standard symbols in the ASCII notation. So we should try to mimick this a bit.

I agree that `-*` looks rather awkward in most fonts.

Here are other proposal that I have seen `-.`, -:`, `->.` (and `-+` above). I would personally not go in the direction of `-:` as it resembles Prolog's logical entailment too much (I find it distracting). My favourite is `->.` though I guess it may be argued that it resembles the regular arrow a bit too much. Also it's three characters long, and it may be annoying that it doesn't align well with standard arrows.

Regarding:

> I do not know whether the notation `λ x ⊸ e` is a good idea. It gives us a linear variant of `λ x → e`, but there is no linear variant of the binding syntax `f x = e`. Maybe we should not think of the arrows in abstractions (“λ-expressions”) as being the same as the arrows in types, but as being analogous to the arrows in, say, case expressions (as in `case of e where p → x`).

On the other hand, the equation syntax will get its linearity information from its signature. That said, it would be more consistent to write something `\(x ::[1] _) -> foo`. It's a tad heavyweight, but is close to the theoretical presentation, and may be applicable to `let` and `case` as well.

**Comment by jeltsch** [comment] 2017-09-05 13:07
I think we can rule out `~>`, `-*`, `-.`, and `-:` then, which leaves `->.` and `-+`.

I am a bit uncomfortable with `->.`. The dot is easy to miss and, as @aspiwack said, `->.` does not align with `->`.

So why not go for `-+`?

**Comment by Tarmean** [comment] 2017-09-05 13:14
I have seen some worry that it might trigger the ligature for ±. Generally that is triggered by +-, though, so I don't think that would be a significant issue.

**Comment by jeltsch** [comment] 2017-09-05 13:16
> > I do not know whether the notation `λ x ⊸ e` is a good idea. It gives us a linear variant of `λ x → e`, but there is no linear variant of the binding syntax `f x = e`. Maybe we should not think of the arrows in abstractions (“λ-expressions”) as being the same as the arrows in types, but as being analogous to the arrows in, say, case expressions (as in `case of e where p → x`).
>
> On the other hand, the equation syntax will get its linearity information from its signature. That said, it would be more consistent to write something `\ (x ::[1] _) -> foo`. It’s a tad heavyweight, but is close to the theoretical presentation, and may be applicable to let and case as well.

An equation will get its linearity information from a signature only if there is a signature.

I did not know that `x ::[1] a` is the proposed notation for type annotations with linearity information. So far, I always saw `x ::1 a`, which I think would be a pretty bad idea, since the parameter `1` would have to be attached to the symbol `::` without a space in order for this to be parsed correctly.

**Comment by aspiwack** [comment] 2017-09-05 13:19
It's not a proposed notation, it's a made-up notation for the sake of the discussion. (`::1` is horrid indeed)

**Comment by jeltsch** [comment] 2017-09-05 13:22
> I have seen some worry that it might trigger the ligature for ±. Generally that is triggered by +-, though, so I don't think that would be a significant issue.

In my opinion, a font where `-+` triggers the ligature `±` is wrong and should be fixed. The symbol `±` is the “plus–minus symbol” and should consequently be triggered by `+-`. However, like @Tarmean, I think that typically `+-`, but not `-+`, triggers `±`.

**Comment by mboes** [comment] 2017-09-05 13:28
> I am a bit uncomfortable with ->.. The dot is easy to miss and, as @aspiwack said, ->. does not align with ->.

It depends on what we are trying to say. A crucial property of linear arrows as designed is that you can largely ignore them. Use a linear function in a non-linear context and none of the linearity matters at all. Use it in a linear context and there the linearity will matter. If `base` is peppered everywhere with `->.` then it's easy enough to convey to people first learning the language that for now they should just assume the dot is immaterial - everything is an arrow.

**Comment by jeltsch** [comment] 2017-09-05 13:51
@mboes: This sounds like a good argument indeed.

**Comment by aspiwack** [comment] 2017-11-09 15:07
Closing: the discussion should now move to ghc-proposals/ghc-proposals#91.

**Closed by aspiwack** 2017-11-09 15:07 UTC
